# Generated by Django 2.2.5 on 2022-04-08 22:12

import apps.media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=400)),
                ('alternate_text', models.CharField(blank=True, max_length=400, null=True)),
                ('source', models.ImageField(blank=True, null=True, upload_to=apps.media.models.get_source_path)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_thumbnails', to='media.Media')),
            ],
            options={
                'verbose_name': 'Media',
            },
        ),
    ]
