# Generated by Django 2.2.5 on 2022-04-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20220408_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='thumbnail',
            new_name='media',
        ),
    ]
