# Generated by Django 2.2.5 on 2022-04-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20220408_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='filepath',
            field=models.CharField(max_length=400),
        ),
    ]
