# Generated by Django 2.2.5 on 2022-04-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casestudy', '0001_initial'),
        ('writeup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudywriteup',
            name='writeup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writeup.Writeup'),
        ),
    ]
