# Generated by Django 2.2.5 on 2022-04-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20220408_2305'),
        ('writeup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteupMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.DecimalField(decimal_places=2, max_digits=3)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeup_medias', to='media.Media')),
                ('writeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeup_medias', to='writeup.Writeup')),
            ],
        ),
    ]
