# Generated by Django 2.2.5 on 2022-04-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0003_writeupsegment_writeupsegmentmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='text',
        ),
    ]
