# Generated by Django 2.2.5 on 2019-09-25 20:37

import apps.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190925_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='brandlogo',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='brandname',
            field=models.CharField(default=apps.portfolio.models.Portfolio.lorem_default, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='brandtypeface',
            field=models.ImageField(null=True, upload_to='portfolio/img/'),
        ),
    ]
