# Generated by Django 2.2.5 on 2019-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190925_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='brandlink',
            field=models.URLField(null=True),
        ),
    ]
