# Generated by Django 2.2.5 on 2022-03-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=20)),
                ('alternate_text', models.CharField(max_length=400, null=True)),
                ('source', models.ImageField(null=True, upload_to='mockup/images/')),
            ],
            options={
                'verbose_name': 'Mockup',
            },
        ),
    ]
