# Generated by Django 2.2.5 on 2022-03-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('mockup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='project.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='mockup',
            unique_together={('project', 'rank')},
        ),
    ]
